package org.budgetwise.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.budgetwise.backend.model.Profile;

@Data
@AllArgsConstructor
@NoArgsConstructor // ✅ Add NoArgsConstructor
public class ProfileDTO {
    private int id;
    private double income;
    private double savings;
    private double targetExpenses;
    private String username;
    private String firstName;
    private String lastName;
    private double totalSpendThisMonth; // ✅ Add this new field

    public static ProfileDTO fromEntity(Profile p) {
        // This constructor will be generated by Lombok's @AllArgsConstructor
        return new ProfileDTO(
                p.getUserId(),
                p.getIncome(),
                p.getSavings(),
                p.getTargetExpenses(),
                p.getUser().getUsername(),
                p.getUser().getFirstName(),
                p.getUser().getLastName(),
                0 // Default value, will be set in the service
        );
    }
}